language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install mocha mssql express
  - npm install
script:
  - npm test
deploy:
  skip_cleanup: true
  github_token: $github_token
  on:
    branch: Development